% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{article}
\usepackage{amsmath,amssymb}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math} % this also loads fontspec
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage{lmodern}
\ifPDFTeX\else
  % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\usepackage[margin=1in]{geometry}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{longtable,booktabs,array}
\usepackage{calc} % for calculating minipage widths
% Correct order of tables after \paragraph or \subparagraph
\usepackage{etoolbox}
\makeatletter
\patchcmd\longtable{\par}{\if@noskipsec\mbox{}\fi\par}{}{}
\makeatother
% Allow footnotes in longtable head/foot
\IfFileExists{footnotehyper.sty}{\usepackage{footnotehyper}}{\usepackage{footnote}}
\makesavenoteenv{longtable}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
\ifLuaTeX
  \usepackage{selnolig}  % disable illegal ligatures
\fi
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same}
\hypersetup{
  pdftitle={Comparação de Alternativas},
  pdfauthor={Coloque seu nome aqui},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}

\title{Comparação de Alternativas}
\author{Coloque seu nome aqui}
\date{Data de entrega: 19/04/2024}

\begin{document}
\maketitle

\hypertarget{descriuxe7uxe3o-da-atividade}{%
\section{Descrição da atividade}\label{descriuxe7uxe3o-da-atividade}}

O objetivo desta atividade é aplicar as técnicas de comparação de
alternativas. A atividade é dividida em duas partes:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  Comparação usando ICs vs.~teste \emph{t}
\item
  Comparação de múltiplas alternativas
\end{enumerate}

Algumas recomendações:

\begin{itemize}
\tightlist
\item
  Se você não estiver habituado com R Markdown, acostume-se a processar
  com frequência o documento, usando o botão \textbf{Knit}. Isso
  permitirá que eventuais erros no documento ou no código R sejam
  identificados rapidamente, pouco depois de terem sido cometidos, o que
  facilitará sua correção. Na verdade, é uma boa ideia você fazer isso
  \textbf{agora}, para garantir que seu ambiente esteja configurado
  corretamente. Se você receber uma mensagem de erro do tipo \emph{Error
  in library(foo)}, isso significa que o pacote \texttt{foo} não está
  instalado. Para instalar um pacote, execute o comando
  \texttt{install.packages("foo")} no Console, ou clique em \emph{Tools}
  -\textgreater{} \emph{Install Packages}.
\item
  Após concluir a atividade, você deverá submeter no Moodle um arquivo
  ZIP contendo:

  \begin{itemize}
  \tightlist
  \item
    o arquivo fonte .Rmd;
  \item
    a saída processada (PDF ou HTML) do arquivo .Rmd;
  \item
    o arquivo de dados referente à Parte 2, que é necessário para o
    processamento do .Rmd.
  \end{itemize}
\end{itemize}

\hypertarget{configurauxe7uxe3o}{%
\section{Configuração}\label{configurauxe7uxe3o}}

Nesta atividade, a única configuração necessária consiste em carregar o
pacote \texttt{ggplot2} e o arquivo \texttt{compar-altern.R}, que são
usados na Parte 1 da atividade.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(ggplot2)}
\FunctionTok{source}\NormalTok{(}\StringTok{"compar{-}altern.R"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\hypertarget{parte-1-comparauxe7uxe3o-usando-ics-vs.-teste-t}{%
\section{\texorpdfstring{Parte 1: Comparação usando ICs vs.~teste
\emph{t}}{Parte 1: Comparação usando ICs vs.~teste t}}\label{parte-1-comparauxe7uxe3o-usando-ics-vs.-teste-t}}

Uma das formas de determinar se duas variáveis são estatisticamente
diferentes é observando os seus intervalos de confiança. Existem três
resultados possíveis para essa comparação:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  \emph{Não existe sobreposição entre os ICs.} Nesse caso, a diferença
  entre as variáveis \textbf{é} estatisticamente significativa.\\
\item
  \emph{Existe sobreposição entre os ICs, e ao menos um deles inclui a
  média da outra variável.} Nesse caso, a diferença entre as variáveis
  \textbf{não é} estatisticamente significativa.
\item
  \emph{Existe sobreposição entre os ICs, mas nenhum deles inclui a
  média da outra variável.} Nesse caso não é possível afirmar nada,
  sendo necessário realizar um teste \emph{t} (ou equivalente) para
  determinar se a diferença é estatisticamente significativa.
\end{enumerate}

O gráfico abaixo ilustra os três resultados. As variáveis comparadas são
as colunas A--F do conjunto de dados contido no arquivo
\texttt{comparacao-ic.dat}, e os ICs têm um nível de confiança de 95\%.
As conclusões visuais são as seguintes:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  As variáveis A e B possuem diferença estatisticamente significativa, e
  A \textless{} B.
\item
  As variáveis C e D não possuem diferença estatisticamente
  significativa.
\item
  Não é possível afirmar se E \textless{} F ou não, é preciso realizar
  um teste \emph{t} para ver se a diferença é estatisticamente
  significativa.
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{dados }\OtherTok{\textless{}{-}} \FunctionTok{read.table}\NormalTok{(}\StringTok{"comparacao{-}ic.dat"}\NormalTok{, }\AttributeTok{head=}\ConstantTok{TRUE}\NormalTok{)}
\NormalTok{dados.ic }\OtherTok{\textless{}{-}} \FunctionTok{geraIC}\NormalTok{(dados)}
\FunctionTok{plotaIC}\NormalTok{(dados.ic)}
\end{Highlighting}
\end{Shaded}

\includegraphics{asc-compar-altern_files/figure-latex/p1-graf-ic-1.pdf}

Para esta primeira parte, você deve comparar os pares de variáveis
representados no gráfico (A/B, C/D, E/F) usando o teste \emph{t} com um
nível de confiança de 95\% (o mesmo usado para gerar os ICs). Para cada
par de variáveis, indique claramente (a) o resultado da comparação (ou
seja, se as variáveis são ou não estatisticamente diferentes) e (b) se
esse resultado é idêntico ao obtido pela comparação visual dos ICs.
Considere que as observações não são pareadas.

\hypertarget{anuxe1lise-e-respostas}{%
\subsubsection{Análise e respostas}\label{anuxe1lise-e-respostas}}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#dados\_stacked \textless{}{-} stack(dados); dados\_stacked}
\CommentTok{\#dados.aov \textless{}{-} aov(values \textasciitilde{} ind, data = dados\_stacked);}
\CommentTok{\#res\_anova \textless{}{-} anova(dados.aov); summary(res\_anova)}

\CommentTok{\#dados.hsd.95 \textless{}{-} TukeyHSD(dados.aov, conf.level = 0.95); dados.hsd.95}
\CommentTok{\#plot(dados.hsd.95, las = 2)}

\CommentTok{\# Parte correta :x}

\NormalTok{ab\_test }\OtherTok{\textless{}{-}} \FunctionTok{t.test}\NormalTok{(dados}\SpecialCharTok{$}\NormalTok{A, dados}\SpecialCharTok{$}\NormalTok{B, }\AttributeTok{conf.level =} \FloatTok{0.95}\NormalTok{);ab\_test}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  Welch Two Sample t-test
## 
## data:  dados$A and dados$B
## t = -4.2872, df = 37.812, p-value = 0.0001202
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  -3.087673 -1.106755
## sample estimates:
## mean of x mean of y 
##  18.83350  20.93072
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{cd\_test }\OtherTok{\textless{}{-}} \FunctionTok{t.test}\NormalTok{(dados}\SpecialCharTok{$}\NormalTok{C, dados}\SpecialCharTok{$}\NormalTok{D, }\AttributeTok{conf.level =} \FloatTok{0.95}\NormalTok{);cd\_test}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  Welch Two Sample t-test
## 
## data:  dados$C and dados$D
## t = -0.60358, df = 35.889, p-value = 0.5499
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  -1.5139020  0.8195255
## sample estimates:
## mean of x mean of y 
##  19.49867  19.84586
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{ef\_test }\OtherTok{\textless{}{-}} \FunctionTok{t.test}\NormalTok{(dados}\SpecialCharTok{$}\NormalTok{E, dados}\SpecialCharTok{$}\NormalTok{F, }\AttributeTok{conf.level =} \FloatTok{0.95}\NormalTok{);ef\_test}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  Welch Two Sample t-test
## 
## data:  dados$E and dados$F
## t = -1.9827, df = 36.821, p-value = 0.0549
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  -2.15377092  0.02353298
## sample estimates:
## mean of x mean of y 
##  19.40222  20.46734
\end{verbatim}

\emph{Respostas aqui}

Resultados com p \textless{} 0.05

B-A: Há uma variação significativa entre as alternativas B-A devido a p
\textless{} 0.05 (0.0001202), resultado identico ao visual C-D: Não há
variação significativa entre as alternativas C-D devido a p
\textgreater{} 0.05 (0.5499), resultado identico ao visual E-F: Não há
variação significativa entre as alternativas C-D devido a p
\textgreater{} 0.05 (0.0549), intevalo de confiança ficou bem proximo de
0 na parte superior porem ainda passa em zero, ou seja, não possui
variação significativa

\hypertarget{parte-2-comparauxe7uxe3o-de-truxeas-algoritmos-de-ordenauxe7uxe3o}{%
\section{Parte 2: Comparação de três algoritmos de
ordenação}\label{parte-2-comparauxe7uxe3o-de-truxeas-algoritmos-de-ordenauxe7uxe3o}}

Na segunda parte iremos comparar o tempo de execução de três algoritmos
de ordenação, \emph{QuickSort}, \emph{MergeSort} e \emph{HeapSort}.
Esses três algoritmos têm complexidade \(O(n \log n)\) no caso médio, e
são considerados eficientes. Para essa comparação iremos usar tempos de
execução medidos pelo script Python \texttt{sortcomp3.py}. Esse script
mede o tempo que cada algoritmo leva para ordenar um vetor de \texttt{n}
elementos (em uma rodada, cada algoritmo ordena um vetor diferente,
sempre de tamanho \texttt{n}). O número de rodadas pode ser passado como
parâmetro na linha de comando (por \emph{default} são realizadas 3
rodadas). A cada rodada os elementos do vetor sofrem uma permutação
aleatória; logo, é possível (mas pouco provável) que o vetor esteja
(quase) em ordem (de)crescente.

O script pode ser executado no RStudio, incluindo a versão Cloud. Na
janela inferior esquerda, normalmente usada para o console, há uma aba
Terminal, na qual você pode executar comandos do Linux.

Neste experimento, primeiro execute o script usando o comando
\texttt{python\ sortcomp3.py\ 2}. O número de rodadas (2, no exemplo)
fica a seu critério.

A seguir, faça uma análise de variância adotando um nível de confiança
de 95\%, e responda aos seguintes itens:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  Qual a porcentagem de variação que pode ser explicada pelas
  alternativas e qual a porcentagem explicada pelo ruído das medições?
\item
  Mostre a tabela ANOVA (conforme o esquema abaixo) e determine se
  existem diferenças estatisticamente significativas entre os tempos
  médios de resposta de cada algoritmo.

  \begin{longtable}[]{@{}llll@{}}
  \toprule\noalign{}
  Fonte de variação & Alternativas & Erros & Total \\
  \midrule\noalign{}
  \endhead
  \bottomrule\noalign{}
  \endlastfoot
  Soma de quadrados & & & \\
  Graus de liberdade & & & \\
  Média quadrática & & & \\
  \emph{F} calculado & & & \\
  \emph{F} crítico & & & \\
  \end{longtable}
\item
  Caso a ANOVA indique que há diferenças estatisticamente
  significativas, ranqueie os algoritmos de acordo com o seu tempo médio
  de resposta (use o teste de Tukey).
\end{enumerate}

Lembre-se que os tempos de execução dos algoritmos devem ser salvos em
um arquivo de dados para que sua análise seja reproduzível. Para
facilitar essa tarefa, o script já gera a saída em um formato
apropriado; você pode redirecionar a saída do script para um arquivo
(por exemplo,
\texttt{python\ sortcomp3.py\ 2\ \textgreater{}parte2.dat}) ou
simplesmente criar o arquivo de dados no próprio editor do RStudio (crie
um novo arquivo texto e cole a saída do script).

\hypertarget{anuxe1lise-e-respostas-1}{%
\subsubsection{Análise e respostas}\label{anuxe1lise-e-respostas-1}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{dados }\OtherTok{\textless{}{-}} \FunctionTok{read.table}\NormalTok{(}\StringTok{"sort{-}comp.dat"}\NormalTok{, }\AttributeTok{head=}\ConstantTok{TRUE}\NormalTok{)}

\NormalTok{dados\_stacked }\OtherTok{\textless{}{-}} \FunctionTok{stack}\NormalTok{(dados); dados\_stacked}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##     values   ind
## 1  0.38173 merge
## 2  0.37101 merge
## 3  0.37064 merge
## 4  0.37678 merge
## 5  0.37372 merge
## 6  0.37726 merge
## 7  0.41607 merge
## 8  0.47015 merge
## 9  0.41867 merge
## 10 0.39408 merge
## 11 0.59992  heap
## 12 0.60658  heap
## 13 0.61790  heap
## 14 0.60582  heap
## 15 0.60584  heap
## 16 0.64628  heap
## 17 0.68850  heap
## 18 0.65305  heap
## 19 0.63552  heap
## 20 0.61077  heap
## 21 0.16215 quick
## 22 0.14867 quick
## 23 0.15150 quick
## 24 0.15725 quick
## 25 0.15380 quick
## 26 0.17388 quick
## 27 0.24066 quick
## 28 0.14972 quick
## 29 0.17507 quick
## 30 0.15438 quick
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{dados.aov }\OtherTok{\textless{}{-}} \FunctionTok{aov}\NormalTok{(values }\SpecialCharTok{\textasciitilde{}}\NormalTok{ ind, }\AttributeTok{data =}\NormalTok{ dados\_stacked);}
\NormalTok{res\_anova }\OtherTok{\textless{}{-}} \FunctionTok{anova}\NormalTok{(dados.aov); res\_anova}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Analysis of Variance Table
## 
## Response: values
##           Df  Sum Sq Mean Sq F value    Pr(>F)    
## ind        2 1.05945 0.52972  614.91 < 2.2e-16 ***
## Residuals 27 0.02326 0.00086                      
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#dados.hsd.95 \textless{}{-} TukeyHSD(dados.aov, conf.level = 0.95); dados.hsd.95; }
\CommentTok{\#plot(dados.hsd.95)}
\end{Highlighting}
\end{Shaded}

\emph{Respostas aqui}

\end{document}
